"""
XG Sports Analytics - Backend com TODOS os Jogos ao Vivo + ODDS em Tempo Real
9 de Abril de 2026 - Apenas Jogos em Andamento
"""

from flask import Flask, jsonify
from flask_cors import CORS
import time
from odds import odds_aggregator

app = Flask(__name__)
CORS(app, origins="*")

# TODOS OS JOGOS AO VIVO EM 9 DE ABRIL DE 2026 - APENAS EM ANDAMENTO
LIVE_MATCHES = [
    # EUROPA LEAGUE - EM ANDAMENTO
    {"fixture_id": 1001, "league": {"id": 61, "name": "Europa League", "country": "Europe", "logo": "https://media.api-sports.io/leagues/61.png", "flag": "https://media.api-sports.io/flags/eu.svg"}, "teams": {"home": {"id": 498, "name": "FC Porto", "logo": "https://media.api-sports.io/teams/logos/498.png", "winner": False}, "away": {"id": 67, "name": "Nottingham Forest", "logo": "https://media.api-sports.io/teams/logos/67.png", "winner": False}}, "score": {"home": 1, "away": 1}, "minute": 93, "status": "2H", "status_long": "2nd Half - 93'", "xg": {"home": 1.2, "away": 1.1, "total": 2.3}, "win_probability": {"home": 45.0, "draw": 35.0, "away": 20.0}, "goal_probability": 65.0, "corner_probability": 75.0, "big_chances": {"home": 3, "away": 2, "total": 5}, "big_chances_probability": {"home": 45, "away": 30}, "over_under": {"over_1_5": 95.0, "under_1_5": 5.0, "over_2_5": 55.0, "under_2_5": 45.0, "over_3_5": 25.0, "under_3_5": 75.0, "expected_total_goals": 2.3, "expected_remaining_goals": 0.2}, "ranking_score": 48.5, "statistics": {"home": {"shots_on_goal": 5, "shots_off_goal": 3, "total_shots": 12, "shots_inside_box": 3, "shots_outside_box": 9, "blocked_shots": 2, "fouls": 12, "corners": 8, "offsides": 1, "possession": 52, "yellow_cards": 2, "red_cards": 0, "saves": 4, "total_passes": 450, "accurate_passes": 380, "passes_pct": 84.4, "attacks": 45, "dangerous_attacks": 12}, "away": {"shots_on_goal": 4, "shots_off_goal": 2, "total_shots": 10, "shots_inside_box": 2, "shots_outside_box": 8, "blocked_shots": 1, "fouls": 14, "corners": 6, "offsides": 2, "possession": 48, "yellow_cards": 1, "red_cards": 0, "saves": 5, "total_passes": 420, "accurate_passes": 350, "passes_pct": 83.3, "attacks": 38, "dangerous_attacks": 10}}},
    {"fixture_id": 1002, "league": {"id": 61, "name": "Europa League", "country": "Europe", "logo": "https://media.api-sports.io/leagues/61.png", "flag": "https://media.api-sports.io/flags/eu.svg"}, "teams": {"home": {"id": 49, "name": "Crystal Palace", "logo": "https://media.api-sports.io/teams/logos/49.png", "winner": True}, "away": {"id": 99, "name": "Fiorentina", "logo": "https://media.api-sports.io/teams/logos/99.png", "winner": False}}, "score": {"home": 2, "away": 0}, "minute": 90, "status": "2H", "status_long": "2nd Half - 90'", "xg": {"home": 1.8, "away": 0.6, "total": 2.4}, "win_probability": {"home": 72.0, "draw": 18.0, "away": 10.0}, "goal_probability": 78.0, "corner_probability": 82.0, "big_chances": {"home": 4, "away": 1, "total": 5}, "big_chances_probability": {"home": 60, "away": 15}, "over_under": {"over_1_5": 98.0, "under_1_5": 2.0, "over_2_5": 65.0, "under_2_5": 35.0, "over_3_5": 30.0, "under_3_5": 70.0, "expected_total_goals": 2.4, "expected_remaining_goals": 0.4}, "ranking_score": 52.3, "statistics": {"home": {"shots_on_goal": 6, "shots_off_goal": 2, "total_shots": 14, "shots_inside_box": 4, "shots_outside_box": 10, "blocked_shots": 1, "fouls": 10, "corners": 9, "offsides": 0, "possession": 58, "yellow_cards": 1, "red_cards": 0, "saves": 2, "total_passes": 480, "accurate_passes": 410, "passes_pct": 85.4, "attacks": 52, "dangerous_attacks": 14}, "away": {"shots_on_goal": 2, "shots_off_goal": 1, "total_shots": 6, "shots_inside_box": 1, "shots_outside_box": 5, "blocked_shots": 2, "fouls": 15, "corners": 4, "offsides": 1, "possession": 42, "yellow_cards": 2, "red_cards": 0, "saves": 6, "total_passes": 350, "accurate_passes": 280, "passes_pct": 80.0, "attacks": 25, "dangerous_attacks": 5}}},
    {"fixture_id": 1003, "league": {"id": 78, "name": "Bundesliga", "country": "Germany", "logo": "https://media.api-sports.io/leagues/78.png", "flag": "https://media.api-sports.io/flags/de.svg"}, "teams": {"home": {"id": 165, "name": "Mainz 05", "logo": "https://media.api-sports.io/teams/logos/165.png", "winner": True}, "away": {"id": 131, "name": "Strasbourg", "logo": "https://media.api-sports.io/teams/logos/131.png", "winner": False}}, "score": {"home": 2, "away": 0}, "minute": 95, "status": "2H", "status_long": "2nd Half - 95'", "xg": {"home": 1.9, "away": 0.5, "total": 2.4}, "win_probability": {"home": 75.0, "draw": 15.0, "away": 10.0}, "goal_probability": 80.0, "corner_probability": 85.0, "big_chances": {"home": 4, "away": 1, "total": 5}, "big_chances_probability": {"home": 60, "away": 15}, "over_under": {"over_1_5": 99.0, "under_1_5": 1.0, "over_2_5": 70.0, "under_2_5": 30.0, "over_3_5": 35.0, "under_3_5": 65.0, "expected_total_goals": 2.4, "expected_remaining_goals": 0.4}, "ranking_score": 53.2, "statistics": {"home": {"shots_on_goal": 7, "shots_off_goal": 1, "total_shots": 15, "shots_inside_box": 4, "shots_outside_box": 11, "blocked_shots": 0, "fouls": 9, "corners": 10, "offsides": 0, "possession": 60, "yellow_cards": 0, "red_cards": 0, "saves": 1, "total_passes": 500, "accurate_passes": 430, "passes_pct": 86.0, "attacks": 55, "dangerous_attacks": 15}, "away": {"shots_on_goal": 1, "shots_off_goal": 2, "total_shots": 5, "shots_inside_box": 1, "shots_outside_box": 4, "blocked_shots": 3, "fouls": 16, "corners": 3, "offsides": 2, "possession": 40, "yellow_cards": 3, "red_cards": 0, "saves": 7, "total_passes": 330, "accurate_passes": 260, "passes_pct": 78.8, "attacks": 20, "dangerous_attacks": 4}}},
    {"fixture_id": 1004, "league": {"id": 61, "name": "Europa League", "country": "Europe", "logo": "https://media.api-sports.io/leagues/61.png", "flag": "https://media.api-sports.io/flags/eu.svg"}, "teams": {"home": {"id": 212, "name": "Shakhtar Donetsk", "logo": "https://media.api-sports.io/teams/logos/212.png", "winner": True}, "away": {"id": 301, "name": "AZ Alkmaar", "logo": "https://media.api-sports.io/teams/logos/301.png", "winner": False}}, "score": {"home": 3, "away": 0}, "minute": 92, "status": "2H", "status_long": "2nd Half - 92'", "xg": {"home": 2.1, "away": 0.4, "total": 2.5}, "win_probability": {"home": 80.0, "draw": 12.0, "away": 8.0}, "goal_probability": 85.0, "corner_probability": 88.0, "big_chances": {"home": 5, "away": 0, "total": 5}, "big_chances_probability": {"home": 75, "away": 0}, "over_under": {"over_1_5": 100.0, "under_1_5": 0.0, "over_2_5": 85.0, "under_2_5": 15.0, "over_3_5": 50.0, "under_3_5": 50.0, "expected_total_goals": 2.5, "expected_remaining_goals": 0.5}, "ranking_score": 56.8, "statistics": {"home": {"shots_on_goal": 8, "shots_off_goal": 0, "total_shots": 16, "shots_inside_box": 5, "shots_outside_box": 11, "blocked_shots": 0, "fouls": 8, "corners": 11, "offsides": 0, "possession": 65, "yellow_cards": 0, "red_cards": 0, "saves": 0, "total_passes": 520, "accurate_passes": 450, "passes_pct": 86.5, "attacks": 60, "dangerous_attacks": 18}, "away": {"shots_on_goal": 0, "shots_off_goal": 1, "total_shots": 3, "shots_inside_box": 0, "shots_outside_box": 3, "blocked_shots": 4, "fouls": 18, "corners": 2, "offsides": 3, "possession": 35, "yellow_cards": 4, "red_cards": 0, "saves": 8, "total_passes": 290, "accurate_passes": 220, "passes_pct": 75.9, "attacks": 15, "dangerous_attacks": 2}}},
    
    # BRASIL - SERIE A - EM ANDAMENTO
    {"fixture_id": 5001, "league": {"id": 71, "name": "Série A", "country": "Brazil", "logo": "https://media.api-sports.io/leagues/71.png", "flag": "https://media.api-sports.io/flags/br.svg"}, "teams": {"home": {"id": 5001, "name": "Tombense", "logo": "https://media.api-sports.io/teams/logos/5001.png", "winner": False}, "away": {"id": 5002, "name": "America MG", "logo": "https://media.api-sports.io/teams/logos/5002.png", "winner": False}}, "score": {"home": 3, "away": 3}, "minute": 87, "status": "2H", "status_long": "2nd Half - 87'", "xg": {"home": 1.6, "away": 1.8, "total": 3.4}, "win_probability": {"home": 38.0, "draw": 28.0, "away": 34.0}, "goal_probability": 85.0, "corner_probability": 80.0, "big_chances": {"home": 3, "away": 4, "total": 7}, "big_chances_probability": {"home": 45, "away": 58}, "over_under": {"over_1_5": 100.0, "under_1_5": 0.0, "over_2_5": 88.0, "under_2_5": 12.0, "over_3_5": 58.0, "under_3_5": 42.0, "expected_total_goals": 3.4, "expected_remaining_goals": 0.3}, "ranking_score": 58.2, "statistics": {"home": {"shots_on_goal": 6, "shots_off_goal": 2, "total_shots": 13, "shots_inside_box": 4, "shots_outside_box": 9, "blocked_shots": 1, "fouls": 11, "corners": 7, "offsides": 1, "possession": 48, "yellow_cards": 2, "red_cards": 0, "saves": 3, "total_passes": 410, "accurate_passes": 340, "passes_pct": 82.9, "attacks": 45, "dangerous_attacks": 11}, "away": {"shots_on_goal": 7, "shots_off_goal": 1, "total_shots": 14, "shots_inside_box": 5, "shots_outside_box": 9, "blocked_shots": 0, "fouls": 10, "corners": 8, "offsides": 0, "possession": 52, "yellow_cards": 1, "red_cards": 0, "saves": 3, "total_passes": 440, "accurate_passes": 370, "passes_pct": 84.1, "attacks": 50, "dangerous_attacks": 13}}},
    
    # LIBERTADORES - EM ANDAMENTO
    {"fixture_id": 7001, "league": {"id": 130, "name": "Copa Libertadores", "country": "South America", "logo": "https://media.api-sports.io/leagues/130.png", "flag": "https://media.api-sports.io/flags/sa.svg"}, "teams": {"home": {"id": 7001, "name": "Cusco", "logo": "https://media.api-sports.io/teams/logos/7001.png", "winner": False}, "away": {"id": 7002, "name": "Flamengo RJ", "logo": "https://media.api-sports.io/teams/logos/7002.png", "winner": True}}, "score": {"home": 0, "away": 2}, "minute": 78, "status": "2H", "status_long": "2nd Half - 78'", "xg": {"home": 0.6, "away": 1.9, "total": 2.5}, "win_probability": {"home": 18.0, "draw": 20.0, "away": 62.0}, "goal_probability": 72.0, "corner_probability": 75.0, "big_chances": {"home": 1, "away": 4, "total": 5}, "big_chances_probability": {"home": 15, "away": 62}, "over_under": {"over_1_5": 95.0, "under_1_5": 5.0, "over_2_5": 58.0, "under_2_5": 42.0, "over_3_5": 28.0, "under_3_5": 72.0, "expected_total_goals": 2.5, "expected_remaining_goals": 0.5}, "ranking_score": 47.2, "statistics": {"home": {"shots_on_goal": 2, "shots_off_goal": 1, "total_shots": 6, "shots_inside_box": 1, "shots_outside_box": 5, "blocked_shots": 2, "fouls": 13, "corners": 3, "offsides": 1, "possession": 38, "yellow_cards": 2, "red_cards": 0, "saves": 2, "total_passes": 310, "accurate_passes": 250, "passes_pct": 80.6, "attacks": 22, "dangerous_attacks": 4}, "away": {"shots_on_goal": 5, "shots_off_goal": 1, "total_shots": 12, "shots_inside_box": 4, "shots_outside_box": 8, "blocked_shots": 0, "fouls": 11, "corners": 7, "offsides": 0, "possession": 62, "yellow_cards": 1, "red_cards": 0, "saves": 2, "total_passes": 510, "accurate_passes": 430, "passes_pct": 84.3, "attacks": 52, "dangerous_attacks": 14}}},
    {"fixture_id": 7002, "league": {"id": 130, "name": "Copa Libertadores", "country": "South America", "logo": "https://media.api-sports.io/leagues/130.png", "flag": "https://media.api-sports.io/flags/sa.svg"}, "teams": {"home": {"id": 7003, "name": "Junior", "logo": "https://media.api-sports.io/teams/logos/7003.png", "winner": False}, "away": {"id": 7004, "name": "Palmeiras", "logo": "https://media.api-sports.io/teams/logos/7004.png", "winner": False}}, "score": {"home": 1, "away": 1}, "minute": 82, "status": "2H", "status_long": "2nd Half - 82'", "xg": {"home": 1.2, "away": 1.3, "total": 2.5}, "win_probability": {"home": 40.0, "draw": 28.0, "away": 32.0}, "goal_probability": 74.0, "corner_probability": 78.0, "big_chances": {"home": 2, "away": 3, "total": 5}, "big_chances_probability": {"home": 32, "away": 48}, "over_under": {"over_1_5": 95.0, "under_1_5": 5.0, "over_2_5": 60.0, "under_2_5": 40.0, "over_3_5": 30.0, "under_3_5": 70.0, "expected_total_goals": 2.5, "expected_remaining_goals": 0.6}, "ranking_score": 46.8, "statistics": {"home": {"shots_on_goal": 4, "shots_off_goal": 1, "total_shots": 10, "shots_inside_box": 3, "shots_outside_box": 7, "blocked_shots": 1, "fouls": 12, "corners": 5, "offsides": 1, "possession": 48, "yellow_cards": 1, "red_cards": 0, "saves": 1, "total_passes": 400, "accurate_passes": 330, "passes_pct": 82.5, "attacks": 40, "dangerous_attacks": 9}, "away": {"shots_on_goal": 4, "shots_off_goal": 2, "total_shots": 11, "shots_inside_box": 3, "shots_outside_box": 8, "blocked_shots": 1, "fouls": 11, "corners": 6, "offsides": 0, "possession": 52, "yellow_cards": 0, "red_cards": 0, "saves": 1, "total_passes": 430, "accurate_passes": 360, "passes_pct": 83.7, "attacks": 45, "dangerous_attacks": 11}}},
    {"fixture_id": 7003, "league": {"id": 130, "name": "Copa Libertadores", "country": "South America", "logo": "https://media.api-sports.io/leagues/130.png", "flag": "https://media.api-sports.io/flags/sa.svg"}, "teams": {"home": {"id": 7005, "name": "Sporting Cristal", "logo": "https://media.api-sports.io/teams/logos/7005.png", "winner": True}, "away": {"id": 7006, "name": "Cerro Porteno", "logo": "https://media.api-sports.io/teams/logos/7006.png", "winner": False}}, "score": {"home": 1, "away": 0}, "minute": 75, "status": "2H", "status_long": "2nd Half - 75'", "xg": {"home": 1.5, "away": 0.4, "total": 1.9}, "win_probability": {"home": 70.0, "draw": 18.0, "away": 12.0}, "goal_probability": 65.0, "corner_probability": 72.0, "big_chances": {"home": 3, "away": 0, "total": 3}, "big_chances_probability": {"home": 58, "away": 0}, "over_under": {"over_1_5": 90.0, "under_1_5": 10.0, "over_2_5": 50.0, "under_2_5": 50.0, "over_3_5": 25.0, "under_3_5": 75.0, "expected_total_goals": 1.9, "expected_remaining_goals": 0.7}, "ranking_score": 43.5, "statistics": {"home": {"shots_on_goal": 4, "shots_off_goal": 1, "total_shots": 10, "shots_inside_box": 3, "shots_outside_box": 7, "blocked_shots": 1, "fouls": 10, "corners": 6, "offsides": 0, "possession": 58, "yellow_cards": 0, "red_cards": 0, "saves": 1, "total_passes": 470, "accurate_passes": 400, "passes_pct": 85.1, "attacks": 48, "dangerous_attacks": 11}, "away": {"shots_on_goal": 1, "shots_off_goal": 0, "total_shots": 3, "shots_inside_box": 1, "shots_outside_box": 2, "blocked_shots": 2, "fouls": 13, "corners": 2, "offsides": 1, "possession": 42, "yellow_cards": 2, "red_cards": 0, "saves": 4, "total_passes": 340, "accurate_passes": 270, "passes_pct": 79.4, "attacks": 20, "dangerous_attacks": 3}}},
]

@app.route('/api/live-matches', methods=['GET'])
def get_live_matches():
    """Retorna apenas jogos EM ANDAMENTO (não finalizados) COM ODDS"""
    # Filtrar apenas jogos em andamento (status 1H ou 2H)
    live_only = [m for m in LIVE_MATCHES if m['status'] in ['1H', '2H']]
    sorted_matches = sorted(live_only, key=lambda m: m['ranking_score'], reverse=True)
    
    # Adicionar odds a cada partida
    for match in sorted_matches:
        match['odds'] = odds_aggregator.get_best_odds(match['fixture_id'])
    
    return jsonify({
        "success": True,
        "count": len(sorted_matches),
        "matches": sorted_matches,
        "last_updated": time.strftime("%Y-%m-%d %H:%M:%S"),
        "data_source": "Live Matches In Progress - April 9, 2026",
        "matches_status": "LIVE NOW",
        "total_leagues": len(set(m['league']['name'] for m in sorted_matches)),
        "total_countries": len(set(m['league']['country'] for m in sorted_matches))
    })

@app.route('/api/match/<int:fixture_id>/odds', methods=['GET'])
def get_match_odds(fixture_id):
    """Retorna odds para uma partida específica"""
    odds = odds_aggregator.get_best_odds(fixture_id)
    return jsonify({
        "success": True,
        "fixture_id": fixture_id,
        "odds": odds,
        "last_updated": time.strftime("%Y-%m-%d %H:%M:%S")
    })

@app.route('/api/status', methods=['GET'])
def get_status():
    live_only = [m for m in LIVE_MATCHES if m['status'] in ['1H', '2H']]
    return jsonify({
        "status": "ok",
        "version": "6.0",
        "data_source": "Live Matches with Odds",
        "matches_count": len(live_only),
        "leagues_count": len(set(m['league']['name'] for m in live_only)),
        "countries_count": len(set(m['league']['country'] for m in live_only)),
        "odds_enabled": True
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
